import { useState,useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { getPortfolio,transaction } from '../../api';import { storage } from '../../stores/cache';import { useThemeColors } from '../../hooks/useThemeColors';
export default function AdjustHoldingPage(){const c=useThemeColors();const nav=useNavigate();const [hs,setHs]=useState<any[]>([]);const [sel,setSel]=useState<any>(null);const [type,setType]=useState<'buy'|'sell'>('buy');const [amount,setAmount]=useState('');const [price,setPrice]=useState('');const [note,setNote]=useState('');const [l,setL]=useState(false);
  useEffect(()=>{(async()=>{try{const r=await getPortfolio();if(r.code===0)setHs(r.data?.holdings||[])}catch{}})()},[]);
  const save=async()=>{if(!sel||!amount){alert('请选择基金并输入金额');return}setL(true);try{await transaction.add({fundCode:sel.fundCode,fundName:sel.fundName,type,amount:parseFloat(amount),price:price?parseFloat(price):undefined,note});storage.set('portfolio_force_refresh',true);storage.remove('portfolio_cache');alert('记录成功');nav(-1)}catch{alert('保存失败')}setL(false)};
  return <div style={{minHeight:'100vh',background:c.bg}}><div style={{padding:'10px 16px',background:c.cardBg,display:'flex'}}><span onClick={()=>nav(-1)} style={{fontSize:18,cursor:'pointer',marginRight:12}}>‹</span><span style={{fontWeight:600,fontSize:16}}>加减仓</span></div>
    <div style={{margin:10,padding:16,background:c.cardBg,borderRadius:12}}>
      <div style={{marginBottom:16}}><div style={{fontSize:13,color:c.textSecondary,marginBottom:4}}>选择基金</div><div style={{display:'flex',flexWrap:'wrap',gap:6}}>{hs.map(h=><div key={h._id} onClick={()=>setSel(h)} style={{padding:'6px 12px',borderRadius:8,border:`1px solid ${sel?._id===h._id?c.primary:c.border}`,background:sel?._id===h._id?c.primaryBg:c.cardBg,fontSize:13,cursor:'pointer'}}>{h.fundName}</div>)}</div></div>
      {sel&&<><div style={{marginBottom:16}}><div style={{display:'flex',borderRadius:8,overflow:'hidden',border:`1px solid ${c.border}`}}><div onClick={()=>setType('buy')} style={{flex:1,textAlign:'center',padding:10,cursor:'pointer',background:type==='buy'?c.up:c.cardBg,color:type==='buy'?c.cardBg:c.text,fontWeight:type==='buy'?600:400}}>买入</div><div onClick={()=>setType('sell')} style={{flex:1,textAlign:'center',padding:10,cursor:'pointer',background:type==='sell'?c.down:c.cardBg,color:type==='sell'?c.cardBg:c.text,fontWeight:type==='sell'?600:400}}>卖出</div></div></div>
      {[{l:'金额（元）',v:amount,on:(e:any)=>setAmount(e.target.value),ph:'交易金额'},{l:'净值（选填）',v:price,on:(e:any)=>setPrice(e.target.value),ph:'成交净值'}].map(f=><div key={f.l} style={{marginBottom:12}}><div style={{fontSize:13,color:c.textSecondary,marginBottom:4}}>{f.l}</div><input value={f.v} onChange={f.on} type="number" placeholder={f.ph} style={{width:'100%',padding:'8px 12px',borderRadius:8,border:`1px solid ${c.border}`,outline:'none',fontSize:14,background:c.cardBg}}/></div>)}
      <div style={{marginBottom:16}}><input value={note} onChange={e=>setNote(e.target.value)} placeholder="备注（选填）" style={{width:'100%',padding:'8px 12px',borderRadius:8,border:`1px solid ${c.border}`,outline:'none',fontSize:14,background:c.cardBg}}/></div>
      <button onClick={save} disabled={l} style={{width:'100%',padding:12,borderRadius:24,border:'none',background:l?c.textHint:type==='buy'?c.up:c.down,color:c.cardBg,fontSize:16,cursor:'pointer'}}>{l?'保存中...':`确认${type==='buy'?'买入':'卖出'}`}</button></>} {hs.length===0&&<div style={{textAlign:'center',padding:32,color:c.textSecondary}}>暂无持仓</div>}</div></div>;
}
