import { useState,useEffect } from 'react';import { useNavigate,useSearchParams } from 'react-router-dom';import { fetchFundInfo,fetchFundNAVHistory,watchlist } from '../../api';import { useUserStore } from '../../stores/user';import { useThemeColors } from '../../hooks/useThemeColors';import DualLineChart from '../../components/Charts/DualLineChart';
export default function FundComparePage(){const c=useThemeColors();const nav=useNavigate();const [p]=useSearchParams();const {isLoggedIn}=useUserStore();const [a,setA]=useState<any>(null);const [b,setB]=useState<any>(null);const [sb,setSb]=useState('');const [wl,setWl]=useState<any[]>([]);const [da,setDa]=useState<any[]>([]);const [db,setDb]=useState<any[]>([]);
  useEffect(()=>{if(p.get('b')){fetchFundInfo(p.get('b')!).then(r=>{if(r.code===0)setA(r.data)})}if(isLoggedIn){watchlist.list().then(r=>{if(r.code===0)setWl(r.data||[])})}},[p,isLoggedIn]);
  const pick=async(code:string,name:string)=>{const r=await fetchFundNAVHistory(code,90);if(r.code===0){const nd=r.data||[];if(!a){setA({fundCode:code,fundName:name});setDa(nd)}else{setB({fundCode:code,fundName:name});setDb(nd)}if(!b&&a)setDb(nd);if(b&&!a)setDa(nd)}};
  useEffect(()=>{if(a&&b){(async()=>{const[ra,rb]=await Promise.all([fetchFundNAVHistory(a.fundCode,90),fetchFundNAVHistory(b.fundCode,90)]);if(ra.code===0)setDa(ra.data||[]);if(rb.code===0)setDb(rb.data||[])})()}},[a,b]);
  const merged=new Map<string,{a:number;b:number}>();if(da.length&&db.length){const ba=da[da.length-1]?.nav||1;const bb=db[db.length-1]?.nav||1;const ma=Object.fromEntries(da.map(d=>[d.date,((d.nav-ba)/ba)*100]));const mb=Object.fromEntries(db.map(d=>[d.date,((d.nav-bb)/bb)*100]));new Set([...da.map(d=>d.date),...db.map(d=>d.date)]).forEach(d=>merged.set(d,{a:ma[d]??0,b:mb[d]??0}))}
  const cd=Array.from(merged.entries()).sort().map(([d,v])=>({date:d.slice(5),rateA:v.a,rateB:v.b}));
  return <div style={{minHeight:'100vh',background:c.bg,paddingBottom:40}}><div style={{padding:'10px 16px',background:c.cardBg,display:'flex'}}><span onClick={()=>nav(-1)} style={{fontSize:18,cursor:'pointer',marginRight:12}}>‹</span><span style={{fontWeight:600,fontSize:16}}>基金对比</span></div>
    <div style={{display:'flex',margin:10,gap:8,textAlign:'center'}}><div style={{flex:1,background:c.cardBg,borderRadius:12,padding:12}}><div style={{fontSize:14,fontWeight:600}}>{a?.fundName||'基金A'}</div><div style={{fontSize:11,color:c.textSecondary}}>{a?.fundCode||'点击选择'}</div></div><div style={{display:'flex',alignItems:'center',fontSize:18,color:c.textSecondary,fontWeight:700}}>VS</div><div style={{flex:1,background:c.cardBg,borderRadius:12,padding:12}}><div style={{fontSize:14,fontWeight:600}}>{b?.fundName||'基金B'}</div><div style={{fontSize:11,color:c.textSecondary}}>{b?.fundCode||'点击选择'}</div></div></div>
    {(!a||!b)&&<div style={{margin:10,padding:12,background:c.cardBg,borderRadius:12}}><input placeholder="搜索自选基金" value={sb} onChange={e=>setSb(e.target.value)} style={{width:'100%',padding:'8px 12px',borderRadius:8,border:`1px solid ${c.border}`,outline:'none',fontSize:14,background:c.cardBg,marginBottom:8}}/>{wl.filter(w=>w.fundName.includes(sb)||w.fundCode.includes(sb)).slice(0,10).map(w=><div key={w.fundCode} onClick={()=>pick(w.fundCode,w.fundName)} style={{padding:'10px 0',borderBottom:`1px solid ${c.bg}`,cursor:'pointer',fontSize:14}}>{w.fundName}({w.fundCode})</div>)}</div>}
    {cd.length>0&&<div style={{margin:10,padding:12,background:c.cardBg,borderRadius:12}}><DualLineChart data={cd} labelA={a?.fundName||'A'} labelB={b?.fundName||'B'} height={260}/></div>}</div>;
}
